apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventilar-app
spec:
  selector:
    matchLabels:
      app: ventilar-app
  template:
    metadata:
      labels:
        app: ventilar-app
    spec:
      containers:
        - name: ventilar-app
          image: gabtec/test-k8s
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ventilar-app
spec:
  selector:
    app: ventilar-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
