---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventilar-app
spec:
  selector:
    matchLabels:
      app: ventilar-app
  template:
    metadata:
      labels:
        app: ventilar-app
    spec:
      containers:
        - name: ventilar-app
          image: ventilar-app #the name on Kustomize images list
          ports:
            - containerPort: 80
