apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: ventilar

images:
  - name: ventilar-app
    newName: gabtec/test-k8s
    newTag: 1d5ea197182952e5b84df1aabd3eac6bc95ce542
