apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

namespace: ventilar

images:
- name: ventilar-app
  newName: gabtec/test-k8s
  newTag: ad2873de2c2ee1d5ae64096c56f2e342a63c9761
