---
apiVersion: v1
kind: Service
metadata:
  name: ventilar-app
spec:
  selector:
    app: ventilar-app
  type: NodePort
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30276
