name: build_image
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [src]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gabtec/test-k8s:latest, gabtec/test-k8s:${{ github.sha }}
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Kustomize in this worker
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: v5.0.1 #sos
      - name: Runs Kustomize to update k8s manifest file
        run: |
          cd k8s
          kustomize edit set image ventilar-app=gabtec/test-k8s:${GITHUB_SHA}
          cat kustomization.yaml
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "CD Action"
          git commit -am "ci: update `ventilar-app` image tag"
      # git push vai falhar porque no meu repo um user desconhecido is not allowed to push
      - name: Push changes
        uses: ad-m/github-push-action@master
        # must go to repo settings and set workflow permissions to write
